export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CREATE_PROPERTY = 'CREATE_PROPERTY'
export const DELETE_PROPERTY = 'DELETE_PROPERTY'
export const GET_ALL = 'GET_ALL'
export const GET_BY_ID = 'GET_BY_ID'
export const PROPERTY_LOADING = 'PROPERTY_LOADING'
// export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// PROPERTIES_LOADING
